#!/usr/bin/env python3
"""Validate input schemas, labels, duplicates, and split leakage."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import _bootstrap  # noqa: F401

from metadata_matcher.train import validate_data_files
from metadata_matcher.utils import configure_logging, write_json


def build_parser() -> argparse.ArgumentParser:
    """Build the data validation CLI parser."""

    parser = argparse.ArgumentParser(description="Validate fixed A/B/label CSV splits.")
    parser.add_argument(
        "--data-dir", type=Path, default=Path("data_split"),
        help="Directory generated by prepare_dataset.py (default: data_split)",
    )
    parser.add_argument("--train", type=Path, help="Override data-dir/train.csv")
    parser.add_argument(
        "--validation", type=Path, help="Override data-dir/validation.csv"
    )
    parser.add_argument("--test", type=Path, help="Override data-dir/test.csv")
    parser.add_argument(
        "--strict-leakage-check",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Exit non-zero if normalized fields overlap (default: enabled)",
    )
    parser.add_argument("--output", type=Path, help="Optional JSON report path")
    return parser


def main() -> None:
    """Validate data and emit a readable JSON report."""

    args = build_parser().parse_args()
    logger = configure_logging()
    _, _, _, report = validate_data_files(
        args.train,
        args.validation,
        args.test,
        data_dir=args.data_dir,
        strict_leakage_check=args.strict_leakage_check,
        logger=logger,
    )
    if args.output:
        write_json(args.output, report)
        print(f"Validation report: {args.output}")
    else:
        print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
